import torch


SAMPLE_INDEX = 'SAMPLE_INDEX'
TIMESTAMP = 'TIMESTAMP'
PHONE_MEASUREMENT_GYROSCOPE = 'PHONE_MEASUREMENT_GYROSCOPE'
PHONE_MEASUREMENT_ACCELEROMETER = 'PHONE_MEASUREMENT_ACCELEROMETER'
GROUND_TRUTH_NAV_ROTATION_MATRIX = 'GROUND_TRUTH_NAV_ROTATION_MATRIX'
GROUND_TRUTH_NAV_VELOCITY = 'GROUND_TRUTH_NAV_VELOCITY'
GROUND_TRUTH_NAV_POSITION = 'GROUND_TRUTH_NAV_POSITION'
PSEUDO_MEASUREMENT_CAR_VELOCITY_FORWARD = 'PSEUDO_MEASUREMENT_CAR_VELOCITY_FORWARD'
PHONE_MEASUREMENT_NORMALIZED = 'PHONE_MEASUREMENT_NORMALIZED'

FILTER_NAV_ROTATION_MATRIX = 'FILTER_NAV_ROTATION_MATRIX'
FILTER_NAV_VELOCITY = 'FILTER_NAV_VELOCITY'
FILTER_NAV_POSITION = 'FILTER_NAV_POSITION'

TENSOR_EYE1 = torch.eye(1).double()
TENSOR_EYE2 = torch.eye(2).double()
TENSOR_EYE3 = torch.eye(3).double()
TENSOR_EYE6 = torch.eye(6).double()
TENSOR_EYE12 = torch.eye(12).double()
TENSOR_EYE21 = torch.eye(21).double()
